#!/usr/bin/env node
// Copies the protocol's source of truth (spec/*.schema.json and the agent
// instructions in spec/AGENT_INSTRUCTIONS.md) into the SDKs, so every
// implementation validates against exactly the same schema.
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const read = (p) => readFileSync(join(root, p), "utf8");

const schemas = {
  FEEDBACK_SCHEMA: JSON.parse(read("spec/feedback.schema.json")),
  RECORD_SCHEMA: JSON.parse(read("spec/record.schema.json")),
  ACK_SCHEMA: JSON.parse(read("spec/ack.schema.json")),
};

const instructionsMd = read("spec/AGENT_INSTRUCTIONS.md");
function block(name) {
  const m = instructionsMd.match(
    new RegExp(`<!-- BEGIN ${name} -->\\n([\\s\\S]*?)\\n<!-- END ${name} -->`),
  );
  if (!m) throw new Error(`Block ${name} not found in AGENT_INSTRUCTIONS.md`);
  return m[1].trim();
}
const AGENT_FEEDBACK_INSTRUCTIONS = block("AGENT_FEEDBACK_INSTRUCTIONS");
const FEEDBACK_TOOL_DESCRIPTION = block("FEEDBACK_TOOL_DESCRIPTION");

const header = "Generated by scripts/sync-schema.mjs from spec/. Do not edit by hand.";

// TypeScript SDK
const ts = [
  `// ${header}`,
  "",
  ...Object.entries(schemas).map(
    ([name, schema]) => `export const ${name} = ${JSON.stringify(schema, null, 2)} as const;\n`,
  ),
  `export const AGENT_FEEDBACK_INSTRUCTIONS = ${JSON.stringify(AGENT_FEEDBACK_INSTRUCTIONS)};\n`,
  `export const FEEDBACK_TOOL_DESCRIPTION = ${JSON.stringify(FEEDBACK_TOOL_DESCRIPTION)};\n`,
].join("\n");
writeFileSync(join(root, "packages/sdk/src/generated.ts"), ts);

// Python SDK
const pyDir = join(root, "packages/sdk-python/src/backloop");
mkdirSync(pyDir, { recursive: true });
const py = [
  `# ${header}`,
  "import json",
  "",
  ...Object.entries(schemas).map(
    ([name, schema]) => `${name} = json.loads(${JSON.stringify(JSON.stringify(schema))})\n`,
  ),
  `AGENT_FEEDBACK_INSTRUCTIONS = ${JSON.stringify(AGENT_FEEDBACK_INSTRUCTIONS)}\n`,
  `FEEDBACK_TOOL_DESCRIPTION = ${JSON.stringify(FEEDBACK_TOOL_DESCRIPTION)}\n`,
].join("\n");
writeFileSync(join(pyDir, "_generated.py"), py);

console.log("Synced schemas and agent instructions into packages/sdk and packages/sdk-python.");
